export class SpecialPerson {
  name: string;
  idCard: string;
  phone: string;
  jurisdiction: string;
  resourceName: string;
  activityPlace: string;
  activityPlaceDetail: string;
  activityTime: string;
  pushTime: string;
  domicile: string;
  personType: boolean;
  nation: string;
  stayInternetSite: string;
  tjTimeReason: string;
  vehicle: string;
  tjStaySite: string;
  tjContact: string;
  belongings: string;
  virtualIdentity: string;
  peerStaff: string;
  stayStaff: string;
  carNum: string;
  terroristChar: string;
  controlType: string;
  checkSite: string;
  checkPolice: string;
  deleteFlag: boolean;
}
